#15.777 Homework 2 (Spring 2024): Natural Langugage Processing

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow import keras

keras.utils.set_random_seed(42)

# Introduction

This homework assignment will ask you to build models using BoW, GloVE and BERT.

We will work with a famous dataset in natural langauge processing called **20 Newsgroup**,  which consists of posts from an online forum under certain topics such as politics, religion, sports...etc. As the name suggests, there are a total of 20 topics in this dataet. The 20 Newsgroup dataset is a popular benchmark for text classification algorithms.

The entire dataset is quite large. To ensure training takes a reasonable amount of time, we will only choose 6 out of the 20 topics, including topics like religion, space (astronomy) and medicine.

In [ ]:
from sklearn.datasets import fetch_20newsgroups

newsgroups_train = fetch_20newsgroups(subset='train', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'])
newsgroups_test = fetch_20newsgroups(subset='test', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'])

train_df = pd.DataFrame({'text': newsgroups_train.data, 'label': newsgroups_train.target})
test_df = pd.DataFrame({'text': newsgroups_test.data, 'label': newsgroups_test.target})

print(f"""
Train samples: {train_df.shape[0]}
Test samples: {test_df.shape[0]}
""")

train_df.head(10)

Train samples: 3222
Test samples: 2145

                                                text  label
0  From: boylan@pi.eai.iastate.edu (Terran Boylan...      1
1  From: I3150101@dbstu1.rz.tu-bs.de (Benedikt Ro...      0
2  From: snichols@adobe.com (Sherri Nichols)\nSub...      3
3  From: johnm@spudge.lonestar.org (John Munsch)\...      1
4  From: Nanci Ann Miller <nm0w+@andrew.cmu.edu>\...      0
5  From: nsmca@aurora.alaska.edu\nSubject: 30826\...      4
6  From: geb@cs.pitt.edu (Gordon Banks)\nSubject:...      3
7  From: higgins@fnalf.fnal.gov (Bill Higgins-- B...      4
8  From: mmm@cup.portal.com (Mark Robert Thorson)...      3
9  From: daniel@lclark.edu (Daniel Snodgrass)\nSu...      1

The distribution of labels across these 6 classes is fairly balanced.

In [ ]:
train_df['label'].value_counts() / train_df.shape[0]

3    0.184358
2    0.184358
4    0.184047
1    0.181254
0    0.148976
5    0.117008
Name: label, dtype: float64

Let's convert our dependent variable into a 1-hot-encoded vector.

In [ ]:
# Let's turn the target into a dummy vector
y_train = pd.get_dummies(train_df['label']).to_numpy()
y_test = pd.get_dummies(test_df['label']).to_numpy()

y_train[:10]

array([[0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0]], dtype=uint8)

# Problem 1: Bag-of-Words (BoW) Model [30 Points]

In this problem, we will build a bag-of-words model using the text vectorization capabilities of Keras. We will then change some of the parameters of this vectorization process and see how it changes the performance.



## Part (a): Build a Base Model [15 Points]

**Text Vectorization**

Please fill in the code in the following cell. We would like to create a text vectorization layer which uses:

* Maximum of 2000 tokens.
* Unigrams
* Outputs a multi-hot encoded BoW encoding
* Converts text to lower case and strips punctuation

In [ ]:
# Set the maximum number of tokens (which is the size of the vocabulary) to 1000
max_tokens = 2000

# Configure the text vectorization layer
text_vectorization = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_mode = 'multi_hot',
    standardize = 'lower_and_strip_punctuation',
    ngrams=1,
)

# Let's adapt the Text Vectorization layer using the training corpus
text_vectorization.adapt(train_df['text'])

# We vectorize our input with the adapted Text Vectorization layer
X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

pd.DataFrame(X_train, columns = text_vectorization.get_vocabulary())

,[UNK],the,of,to,a,and,in,is,i,that,...,loving,learning,jaegerbuphybuedu,hour,helps,glutamate,finding,delta,careful,bother
0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3218,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3219,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3220,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3221,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In the following cell, please build a simple Neural Network with a single hidden layer of 128 neurons and a ReLu activation function. Be sure to specify the shape of the input correctly and use the appropriate activation function for the output. Your model should have 256902 parameters. The code for compiling, training and computing the test accuracy has been written for you already.

In [ ]:
# Build a baseline NN model with one hidden layer that has 8 neurons.
inputs = keras.Input(shape=(max_tokens, )) # Size of the input layer is the size of the vocabulary
x = keras.layers.Dense(128, activation="relu")(inputs) # only hidden layer
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

# Compile model using Adam
bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_1 (InputLayer)        [(None, 2000)]            0

 dense (Dense)               (None, 128)               256128

 dense_1 (Dense)             (None, 6)                 774

=================================================================
Total params: 256902 (1003.52 KB)
Trainable params: 256902 (1003.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

A theme that we will be investigating in this homework is the **impact of the number of training examples on the various models**. As a result, in addition to training the model on all 3000+ training examples, we will also test how our model performs with only 200 examples.

The code below shows a fitting process in which we first fit model `bow_model` to the first 200 examples from the training set `(X_train[:200], y_train[:200]`). We print the accuracy of the model on the test set. Then, we run the training procedure for another 20 epochs, this time with the full data set `(X_train, y_train`).

In [ ]:
# Fit model on the training data with 10 epochs and batch size of 32
bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Epoch 1/20
7/7 [==============================] - 2s 11ms/step - loss: 1.7121 - accuracy: 0.3350
Epoch 2/20
7/7 [==============================] - 0s 4ms/step - loss: 1.1343 - accuracy: 0.9000
Epoch 3/20
7/7 [==============================] - 0s 3ms/step - loss: 0.7558 - accuracy: 0.9800
Epoch 4/20
7/7 [==============================] - 0s 3ms/step - loss: 0.4887 - accuracy: 0.9950
Epoch 5/20
7/7 [==============================] - 0s 3ms/step - loss: 0.3092 - accuracy: 0.9950
Epoch 6/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1965 - accuracy: 1.0000
Epoch 7/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1284 - accuracy: 1.0000
Epoch 8/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0874 - accuracy: 1.0000
Epoch 9/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0607 - accuracy: 1.0000
Epoch 10/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0446 - accuracy: 1.0000
Epoch 11/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0341 - accuracy: 1.0000
Epoch 12/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0275 - accuracy: 1.0000
Epoch 13/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0222 - accuracy: 1.0000
Epoch 14/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0188 - accuracy: 1.0000
Epoch 15/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0160 - accuracy: 1.0000
Epoch 16/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0139 - accuracy: 1.0000
Epoch 17/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0122 - accuracy: 1.0000
Epoch 18/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0109 - accuracy: 1.0000
Epoch 19/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0097 - accuracy: 1.0000
Epoch 20/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0088 - accuracy: 1.0000
68/68 [==============================] - 0s 3ms/step - loss: 1.0119 - accuracy: 0.6214

*** Test accuracy with 200 Examples: 0.6214 ***

Epoch 1/20
101/101 [==============================] - 0s 3ms/step - loss: 0.4355 - accuracy: 0.8603
Epoch 2/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0987 - accuracy: 0.9808
Epoch 3/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0485 - accuracy: 0.9950
Epoch 4/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0287 - accuracy: 0.9988
Epoch 5/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0182 - accuracy: 0.9997
Epoch 6/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0127 - accuracy: 1.0000
Epoch 7/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0094 - accuracy: 1.0000
Epoch 8/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0072 - accuracy: 1.0000
Epoch 9/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0057 - accuracy: 1.0000
Epoch 10/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0046 - accuracy: 1.0000
Epoch 11/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0038 - accuracy: 1.0000
Epoch 12/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 13/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 14/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0023 - accuracy: 1.0000
Epoch 15/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0020 - accuracy: 1.0000
Epoch 16/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0017 - accuracy: 1.0000
Epoch 17/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0015 - accuracy: 1.0000
Epoch 18/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 19/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0012 - accuracy: 1.0000
Epoch 20/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0011 - accuracy: 1.0000
68/68 [==============================] - 0s 2ms/step - loss: 0.7034 - accuracy: 0.8266

*** Test accuracy with All Examples  0.8266 ***

Please write down the test accuracy shown above and comment on the model's performance. What is the baseline performance by predicting the most frequent class?

* BoW with 200 Examples: 62.14%
* BoW with All Examples: 82.66%

**<font color='red'>Your Answer Here</font>**

_Please fill in the numbers above and replace this text with your brief comment_

_Solution. The model achieves a reasonable accuracy of 82.66%. The baseline in this problem is to predict the majority class, which acheives a 17% accuracy. Unsurprisingly, using fewer training examples leads to worse performance._

## Part (b): Exploring Hyperparameters [15 Points]

Now, let us try changing some of the hyperparameters that in the text vectorization process.

For each of the following modifications, please change the code for Problem 1(a), train the model and report the out-of-sample accuracy below. You do not need to duplicate the code from 1(a) here.

* Use bigrams instead of unigrams.
* Increase the maximum number of tokens from 2000 to 5000
* Use count vectorization instead of multi-hot.

Note that you should make each change independent of the other two changes. <font color='red'>Don't forget to undo each change before making the next </font>

Copy and paste the code from Problem 1(a) into a single cell. Then, make each of the 3 changes above and fill in the table of accuracies.

In [ ]:
# Set the maximum number of tokens (which is the size of the vocabulary) to 1000
max_tokens = 2000

# Configure the text vectorization layer
text_vectorization = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_mode = 'multi_hot',
    standardize = 'lower_and_strip_punctuation',
    ngrams=2,
)

# Let's adapt the Text Vectorization layer using the training corpus
text_vectorization.adapt(train_df['text'])

# We vectorize our input with the adapted Text Vectorization layer
X_train = text_vectorization(train_df['text'])
X_test = text_vectorization(test_df['text'])

# Build a baseline NN model with one hidden layer that has 8 neurons.
inputs = keras.Input(shape=(max_tokens, )) # Size of the input layer is the size of the vocabulary
x = keras.layers.Dense(128, activation="relu")(inputs) # only hidden layer
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)

bow_model = keras.Model(inputs, outputs)
bow_model.summary()

# Compile model using Adam
bow_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 10 epochs and batch size of 32
bow_model.fit(
    x=X_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
bow_model.fit(
    x=X_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model.evaluate(x=X_test, y=y_test)[1])

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_2 (InputLayer)        [(None, 2000)]            0

 dense_2 (Dense)             (None, 128)               256128

 dense_3 (Dense)             (None, 6)                 774

=================================================================
Total params: 256902 (1003.52 KB)
Trainable params: 256902 (1003.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
7/7 [==============================] - 1s 4ms/step - loss: 1.7806 - accuracy: 0.2300
Epoch 2/20
7/7 [==============================] - 0s 3ms/step - loss: 1.1125 - accuracy: 0.8450
Epoch 3/20
7/7 [==============================] - 0s 3ms/step - loss: 0.7096 - accuracy: 0.9900
Epoch 4/20
7/7 [==============================] - 0s 3ms/step - loss: 0.4489 - accuracy: 1.0000
Epoch 5/20
7/7 [==============================] - 0s 5ms/step - loss: 0.2787 - accuracy: 1.0000
Epoch 6/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1770 - accuracy: 1.0000
Epoch 7/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1158 - accuracy: 1.0000
Epoch 8/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0788 - accuracy: 1.0000
Epoch 9/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0553 - accuracy: 1.0000
Epoch 10/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0417 - accuracy: 1.0000
Epoch 11/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0324 - accuracy: 1.0000
Epoch 12/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0265 - accuracy: 1.0000
Epoch 13/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0215 - accuracy: 1.0000
Epoch 14/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0183 - accuracy: 1.0000
Epoch 15/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0157 - accuracy: 1.0000
Epoch 16/20
7/7 [==============================] - 0s 4ms/step - loss: 0.0136 - accuracy: 1.0000
Epoch 17/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0120 - accuracy: 1.0000
Epoch 18/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0107 - accuracy: 1.0000
Epoch 19/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0095 - accuracy: 1.0000
Epoch 20/20
7/7 [==============================] - 0s 3ms/step - loss: 0.0085 - accuracy: 1.0000
68/68 [==============================] - 0s 2ms/step - loss: 1.1679 - accuracy: 0.5664

*** Test accuracy with 200 Examples: 0.5664 ***

Epoch 1/20
101/101 [==============================] - 0s 3ms/step - loss: 0.5298 - accuracy: 0.8178
Epoch 2/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1267 - accuracy: 0.9714
Epoch 3/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0630 - accuracy: 0.9932
Epoch 4/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0380 - accuracy: 0.9969
Epoch 5/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0246 - accuracy: 0.9988
Epoch 6/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0172 - accuracy: 0.9994
Epoch 7/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0128 - accuracy: 0.9997
Epoch 8/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0099 - accuracy: 1.0000
Epoch 9/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0078 - accuracy: 1.0000
Epoch 10/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 11/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0052 - accuracy: 1.0000
Epoch 12/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0044 - accuracy: 1.0000
Epoch 13/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0037 - accuracy: 1.0000
Epoch 14/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0032 - accuracy: 1.0000
Epoch 15/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0027 - accuracy: 1.0000
Epoch 16/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0024 - accuracy: 1.0000
Epoch 17/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0021 - accuracy: 1.0000
Epoch 18/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0018 - accuracy: 1.0000
Epoch 19/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0016 - accuracy: 1.0000
Epoch 20/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0014 - accuracy: 1.0000
68/68 [==============================] - 0s 2ms/step - loss: 0.9409 - accuracy: 0.7800

*** Test accuracy with All Examples  0.7800 ***



Replace the following numbers with the out-of-sample accuracy you obtained from re-running Problem 1(a)'s code with the relevant modifications.

* Bigrams instead of unigrams
  * 200 Training Examples: 56%
  * All Training Examples: 78%
* Increasing max_tokens to 5000.
  * 200 Training Examples: 65%
  * All Training Examples: 87%
* Count instead of multi-hot
  * 200 Training Examples: 61%
  * All Training Examples: 83%

For each of the 3 modifications, discuss why one might expect such a change to be beneficial. Using the numbers above, comment on whether it improved, hurt or didn't affect the model's performance.

**<font color='red'>Your Answer Here</font>**

_Bigrams did not help. We may expect that pairs of words would provide a richer signal than a single word, but that seems to not be the case in this dataset. Note that we added pairs of words, but did not increase the max tokens. By adding pairs of words, we may have added some meaningless bigrams (e.g. "of the") we potentially pushed some useful unigrams out of the vocabulary space._

_Increasing the max token helped. This supports the idea that our vocabulary space of just the top 2000 tokens was not large enough._

_Using count instead of multi-hot did not help. Such a modification could help if the frequency of a word affects its class. For example, in sentiment analysis, there may be both positive and negative words present, but whichever type of word is present more often dictates the sentiment of the entire sentence._

# Problem 2: GloVe without Fine-Tuning [20 Points]

Now, we will train a model using GloVe. We will try using GloVe vectors out of box and with fine-tuning. Let's first download the GloVe vectors from the internet. The code below will take a couple minutes to run.

In [ ]:
!wget -O glove.6B.300d.zip https://www.dropbox.com/scl/fi/ree568j1h690ktpcn729b/glove.6B.300d.zip?rlkey=eq9r67js0n0vm2znvdev9rerf&dl=1
!unzip glove.6B.300d.zip

--2024-02-24 16:00:34--  https://www.dropbox.com/scl/fi/ree568j1h690ktpcn729b/glove.6B.300d.zip?rlkey=eq9r67js0n0vm2znvdev9rerf
Resolving www.dropbox.com (www.dropbox.com)... 162.125.1.18, 2620:100:6016:18::a27d:112
Connecting to www.dropbox.com (www.dropbox.com)|162.125.1.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://ucc382e919c04501702b703f7142.dl.dropboxusercontent.com/cd/0/inline/CN4PMd67U9OVSzis14wkErz3G9RJfgYxcxcU_hAwyhRFu9VL3a3Ee1zN56cYbVxPSDJvNQikpXHFY2tuzNKcYAGr49yWf93QOD5iegFqSwZI7g7N1aKMtT7EFbDPHk0NFy2TrR0g6p8oB1IMi-p5-uWh/file# [following]
--2024-02-24 16:00:35--  https://ucc382e919c04501702b703f7142.dl.dropboxusercontent.com/cd/0/inline/CN4PMd67U9OVSzis14wkErz3G9RJfgYxcxcU_hAwyhRFu9VL3a3Ee1zN56cYbVxPSDJvNQikpXHFY2tuzNKcYAGr49yWf93QOD5iegFqSwZI7g7N1aKMtT7EFbDPHk0NFy2TrR0g6p8oB1IMi-p5-uWh/file
Resolving ucc382e919c04501702b703f7142.dl.dropboxusercontent.com (ucc382e919c04501702b703f7142.dl.dropboxusercontent.com)... 162.125.1.15, 2620:100:6016:15::a27d:10f
Connecting to ucc382e919c04501702b703f7142.dl.dropboxusercontent.com (ucc382e919c04501702b703f7142.dl.dropboxusercontent.com)|162.125.1.15|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /cd/0/inline2/CN4vzos4M82a_HausdKHwwW4fAGs7W0c_PMoB2BMVXYYNQTtgmAnGAs6uZAGXQBxxrqA5FDcDFfmZhJ3YPeZa2QV8OceL3IXrGTTi6SwAwGT7O0ceYGz0xNhzj41ig5QdCYz1sPOZyaDZ8bgdZlAj117JJyr9wM8jJd5qWYz6cz5Lo3lvJIKYsAHfEigZtPW5p7Uu4IZCJP-__ZsBrJ5CkeMQ9QH302Tr8fuo3x00o_nMOUkNw-bp8D0X39TWQ_rjJP1GxRtvEL1OwdUMYb06khFuWSpdbegWMftZgxOMs4bB10DMsgOG-yFSkAq3M1tjcp9u6WiCX5QQQVvhSDGr5GtRWOdZvl6XH-WQfPxDnj-8yPc5Pb6mrKCWuod63DTc9o/file [following]
--2024-02-24 16:00:35--  https://ucc382e919c04501702b703f7142.dl.dropboxusercontent.com/cd/0/inline2/CN4vzos4M82a_HausdKHwwW4fAGs7W0c_PMoB2BMVXYYNQTtgmAnGAs6uZAGXQBxxrqA5FDcDFfmZhJ3YPeZa2QV8OceL3IXrGTTi6SwAwGT7O0ceYGz0xNhzj41ig5QdCYz1sPOZyaDZ8bgdZlAj117JJyr9wM8jJd5qWYz6cz5Lo3lvJIKYsAHfEigZtPW5p7Uu4IZCJP-__ZsBrJ5CkeMQ9QH302Tr8fuo3x00o_nMOUkNw-bp8D0X39TWQ_rjJP1GxRtvEL1OwdUMYb06khFuWSpdbegWMftZgxOMs4bB10DMsgOG-yFSkAq3M1tjcp9u6WiCX5QQQVvhSDGr5GtRWOdZvl6XH-WQfPxDnj-8yPc5Pb6mrKCWuod63DTc9o/file
Reusing existing connection to ucc382e919c04501702b703f7142.dl.dropboxusercontent.com:443.
HTTP request sent, awaiting response... 200 OK
Length: 359766655 (343M) [application/zip]
Saving to: ‘glove.6B.300d.zip’

glove.6B.300d.zip   100%[===================>] 343.10M   117MB/s    in 2.9s

2024-02-24 16:00:39 (117 MB/s) - ‘glove.6B.300d.zip’ saved [359766655/359766655]

Archive:  glove.6B.300d.zip
  inflating: glove.6B.300d.txt

## Part (a): Load Pre-trained Vectors [10 Points]

Let's take the `glove.6B.300d.txt` file, which consists of 300-dimensional vectors for 400,000 words in English.

In [ ]:
embedding_dim = 300
path_to_glove_file = f"glove.6B.{embedding_dim}d.txt"

embeddings_index = {}
with open(path_to_glove_file) as f:
    for line in f:
        word, coefs = line.split(maxsplit=1)
        coefs = np.fromstring(coefs, "f", sep=" ")
        embeddings_index[word] = coefs

print(f"Found {len(embeddings_index)} word vectors.")

Found 400000 word vectors.

For any of these 400,000 words, we can query its 300-dimensional vector

In [ ]:
embeddings_index['hello']

array([-3.3712e-01, -2.1691e-01, -6.6365e-03, -4.1625e-01, -1.2555e+00,
       -2.8466e-02, -7.2195e-01, -5.2887e-01,  7.2085e-03,  3.1997e-01,
        2.9425e-02, -1.3236e-02,  4.3511e-01,  2.5716e-01,  3.8995e-01,
       -1.1968e-01,  1.5035e-01,  4.4762e-01,  2.8407e-01,  4.9339e-01,
        6.2826e-01,  2.2888e-01, -4.0385e-01,  2.7364e-02,  7.3679e-03,
        1.3995e-01,  2.3346e-01,  6.8122e-02,  4.8422e-01, -1.9578e-02,
       -5.4751e-01, -5.4983e-01, -3.4091e-02,  8.0017e-03, -4.3065e-01,
       -1.8969e-02, -8.5670e-02, -8.1123e-01, -2.1080e-01,  3.7784e-01,
       -3.5046e-01,  1.3684e-01, -5.5661e-01,  1.6835e-01, -2.2952e-01,
       -1.6184e-01,  6.7345e-01, -4.6597e-01, -3.1834e-02, -2.6037e-01,
       -1.7797e-01,  1.9436e-02,  1.0727e-01,  6.6534e-01, -3.4836e-01,
        4.7833e-02,  1.6440e-01,  1.4088e-01,  1.9204e-01, -3.5009e-01,
        2.6236e-01,  1.7626e-01, -3.1367e-01,  1.1709e-01,  2.0378e-01,
        6.1775e-01,  4.9075e-01, -7.5210e-02, -1.1815e-01,  1.8685e-01,
        4.0679e-01,  2.8319e-01, -1.6290e-01,  3.8388e-02,  4.3794e-01,
        8.8224e-02,  5.9046e-01, -5.3515e-02,  3.8819e-02,  1.8202e-01,
       -2.7599e-01,  3.9474e-01, -2.0499e-01,  1.7411e-01,  1.0315e-01,
        2.5117e-01, -3.6542e-01,  3.6528e-01,  2.2448e-01, -9.7551e-01,
        9.4505e-02, -1.7859e-01, -3.0688e-01, -5.8633e-01, -1.8526e-01,
        3.9565e-02, -4.2309e-01, -1.5715e-01,  2.0401e-01,  1.6906e-01,
        3.4465e-01, -4.2262e-01,  1.9553e-01,  5.9454e-01, -3.0531e-01,
       -1.0633e-01, -1.9055e-01, -5.8544e-01,  2.1357e-01,  3.8414e-01,
        9.1499e-02,  3.8353e-01,  2.9075e-01,  2.4519e-02,  2.8440e-01,
        6.3715e-02, -1.5483e-01,  4.0031e-01,  3.1543e-01, -3.7128e-02,
        6.3363e-02, -2.7090e-01,  2.5160e-01,  4.7105e-01,  4.9556e-01,
       -3.6401e-01,  1.0370e-01,  4.6076e-02,  1.6565e-01, -2.9024e-01,
       -6.6949e-02, -3.0881e-01,  4.8263e-01,  3.0972e-01, -1.1145e-01,
       -1.0329e-01,  2.8585e-02, -1.3579e-01,  5.2924e-01, -1.4077e-01,
        9.1763e-02,  1.3127e-01, -2.0944e-01,  2.2327e-02, -7.7692e-02,
        7.7934e-02, -3.3067e-02,  1.1680e-01,  3.2029e-01,  3.7749e-01,
       -7.5679e-01, -1.5944e-01,  1.4964e-01,  4.2253e-01,  2.8136e-03,
        2.1328e-01,  8.6776e-02, -5.2704e-02, -4.0859e-01, -1.1774e-01,
        9.0621e-02, -2.3794e-01, -1.8326e-01,  1.3115e-01, -5.5949e-01,
        9.2071e-02, -3.9504e-02,  1.3334e-01,  4.9632e-01,  2.8733e-01,
       -1.8544e-01,  2.4618e-02, -4.2826e-01,  7.4148e-02,  7.6584e-04,
        2.3950e-01,  2.2615e-01,  5.5166e-02, -7.5096e-02, -2.2308e-01,
        2.3775e-01, -4.5455e-01,  2.6564e-01, -1.5137e-01, -2.4146e-01,
       -2.4736e-01,  5.5214e-01,  2.6819e-01,  4.8831e-01, -1.3423e-01,
       -1.5918e-01,  3.7606e-01, -1.9834e-01,  1.6699e-01, -1.5368e-01,
        2.4561e-01, -9.2506e-02, -3.0257e-01, -2.9493e-01, -7.4917e-01,
        1.0567e+00,  3.7971e-01,  6.9314e-01, -3.1672e-02,  2.1588e-01,
       -4.0739e-01, -1.5264e-01,  3.2296e-01, -1.2999e-01, -5.0129e-01,
       -4.4231e-01,  1.6904e-02, -1.1459e-02,  7.2293e-03,  1.1026e-01,
        2.1568e-01, -3.2373e-01, -3.7292e-01, -9.2456e-03, -2.6769e-01,
        3.9066e-01,  3.5742e-01, -6.0632e-02,  6.7966e-02,  3.3830e-01,
        6.5747e-02,  1.5794e-01,  4.7155e-02,  2.3682e-01, -9.1370e-02,
        6.4649e-01, -2.5491e-01, -6.7940e-01, -6.9752e-01, -1.0145e-01,
       -3.6255e-01,  3.6967e-01, -4.1295e-01,  8.2724e-02, -3.5053e-01,
       -1.7564e-01,  8.5095e-02, -5.7724e-01,  5.0252e-01,  5.2180e-01,
        5.7327e-02, -7.9754e-01, -3.7770e-01,  7.8149e-01,  2.4597e-01,
        6.0672e-01, -2.0082e-01, -3.8792e-01,  4.1295e-01, -1.6143e-01,
        1.0427e-02,  4.3197e-01,  4.6297e-03,  2.1185e-01, -2.6606e-01,
       -5.8740e-02, -5.1003e-01,  2.8524e-01,  1.3627e-02, -2.7346e-01,
        6.1848e-02, -5.7901e-01, -5.1136e-01,  3.6382e-01,  3.5144e-01,
       -1.6501e-01, -4.6041e-01, -6.4742e-02, -6.8310e-01, -4.7427e-02,
        1.5861e-01, -4.7288e-01,  3.3968e-01,  1.2092e-03,  1.6018e-01,
       -5.8024e-01,  1.4556e-01, -9.1317e-01, -3.7592e-01, -3.2950e-01,
        5.3465e-01,  1.8224e-01, -5.2265e-01, -2.6209e-01, -4.2458e-01,
       -1.8034e-01,  9.9502e-02, -1.5114e-01, -6.6731e-01,  2.4483e-01,
       -5.6630e-01,  3.3843e-01,  4.0558e-01,  1.8073e-01,  6.4250e-01],
      dtype=float32)

Let's create our vocabulary space from the training data. We do this using the `TextVectorization` layer just like before. However, this time, we choose `output_mode=int`.

In [ ]:
max_length = 400 # For each piece of text, consider only the first 400 tokens (then truncate or pad)
max_tokens = 2000 # Our vocabulary space of tokens can be at most size 5000

text_vectorization_glove = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_mode="int",
    output_sequence_length=max_length,
)

text_vectorization_glove.adapt(train_df['text'])

X_train_glove = text_vectorization_glove(train_df['text'])
X_test_glove = text_vectorization_glove(test_df['text'])

X_train_glove

<tf.Tensor: shape=(3222, 400), dtype=int64, numpy=
array([[  14,    1,    1, ...,    0,    0,    0],
       [  14,    1, 1334, ...,  726,    1,    1],
       [  14,    1,    1, ...,    0,    0,    0],
       ...,
       [  14,    1,   27, ...,  116,    1,    6],
       [  14,  546,  325, ...,    0,    0,    0],
       [  14,    1,    1, ...,    0,    0,    0]])>

In the output above for `X_train_glove`, each row is a training example and the columns represent the _index_ of the token. For example, the first training example starts with token 14, followed by token 1, then token 1,... and ending with the padding tokens 0.

**Question**: What English word does token 14 correspond to? Hint: A cell from the Introduction will help you here.

<font color='red'>**Your Answer Here**</font>

_Replace this with your answer and explain how you know._
_The token 14 corresponds to "From". These newsgroup posts are discussion forums and they start with a from: someone@gmail.com line. We see this when looking at `train_df.head()`_

For each of the 2000 tokens we extracted from our training data, we will look up its vector from `embedding_vector`.

In [ ]:
vocabulary = text_vectorization_glove.get_vocabulary()
word_index = dict(zip(vocabulary, range(len(vocabulary))))

counter = 0
embedding_matrix = np.zeros((max_tokens, embedding_dim))
for word, i in word_index.items():
    if i < max_tokens:
        embedding_vector = embeddings_index.get(word)
    if embedding_vector is not None:
        embedding_matrix[i] = embedding_vector
    else:
        counter += 1

embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.04656   ,  0.21318001, -0.0074364 , ...,  0.0090611 ,
        -0.20988999,  0.053913  ],
       ...,
       [-0.038683  ,  0.32398999,  0.10977   , ...,  0.10819   ,
        -0.22115   , -0.17591   ],
       [ 0.47946   ,  0.23098999, -0.11539   , ..., -0.26082999,
        -0.30032   ,  0.089238  ],
       [ 0.19551   , -0.24070001,  0.36401001, ..., -0.069489  ,
         0.32620001,  0.099097  ]])

The above matrix is of shape 2000 by 300. Each row corresponds to one of the 2000 tokens and the value in the row is the 300-dimensional vectorization of that token. We notice that the first two tokens above (index 0 and index 1) are mapped to the all zeros vector.

**Question:** What tokens are represented by index 0 and index 1?

<font color='red'>**Your Answer Here**</font>

_Replace this with your answer_

_They correspont to the [PAD] and [UNK] tokens_

## Part (b): Build the Model [10 Points]
Now, let's build the model. Fill in the missing code below.

* Create an embedding layer of the appropriate input and output dimensions. Initialize it to `keras.initializers.Constant(embedding_matrix)`, set `trainable=False` and `mask_zero=True`.
* Add a `GlobalAveragePooling1D` layer.
* Followed by a Dense layer with 128 neurons (ReLU activation), then a Dropout layer with probability of dropout 0.2. Follow this by another Dense layer of 128 neurons and a Dropout with 0.2 probability.


Your model should have 655,814 parameters out of which 55,814 are trainable.

In [ ]:
embedding_layer = keras.layers.Embedding(
    max_tokens, # input dimension
    embedding_dim, # output dimension
    embeddings_initializer= keras.initializers.Constant(embedding_matrix),
    trainable=False,
    mask_zero=True,
)

inputs = keras.Input(shape=(max_length,))

x = embedding_layer(inputs)
x = keras.layers.GlobalAveragePooling1D()(x)
x = keras.layers.Dense(128, activation="relu")(x)
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(128, activation="relu")(x)
x = keras.layers.Dropout(0.2)(x)

outputs = keras.layers.Dense(y_train.shape[1], activation="sigmoid")(x) # output layer

glove_model = keras.Model(inputs, outputs)
glove_model.summary()

# Compile model using Adam
glove_model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 10 epochs and batch size of 32
glove_model.fit(
    x=X_train_glove[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples: %.3f ***\n" % glove_model.evaluate(x=X_test_glove, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
glove_model.fit(
    x=X_train_glove, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples: %.3f ***\n" % glove_model.evaluate(x=X_test_glove, y=y_test)[1])

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_3 (InputLayer)        [(None, 400)]             0

 embedding (Embedding)       (None, 400, 300)          600000

 global_average_pooling1d (  (None, 300)               0
 GlobalAveragePooling1D)

 dense_4 (Dense)             (None, 128)               38528

 dropout (Dropout)           (None, 128)               0

 dense_5 (Dense)             (None, 128)               16512

 dropout_1 (Dropout)         (None, 128)               0

 dense_6 (Dense)             (None, 6)                 774

=================================================================
Total params: 655814 (2.50 MB)
Trainable params: 55814 (218.02 KB)
Non-trainable params: 600000 (2.29 MB)
_________________________________________________________________
Epoch 1/20
7/7 [==============================] - 3s 6ms/step - loss: 1.7903 - accuracy: 0.2000
Epoch 2/20
7/7 [==============================] - 0s 4ms/step - loss: 1.7595 - accuracy: 0.2200
Epoch 3/20
7/7 [==============================] - 0s 4ms/step - loss: 1.7464 - accuracy: 0.2550
Epoch 4/20
7/7 [==============================] - 0s 4ms/step - loss: 1.7396 - accuracy: 0.2550
Epoch 5/20
7/7 [==============================] - 0s 4ms/step - loss: 1.7008 - accuracy: 0.2950
Epoch 6/20
7/7 [==============================] - 0s 5ms/step - loss: 1.6816 - accuracy: 0.3300
Epoch 7/20
7/7 [==============================] - 0s 5ms/step - loss: 1.6760 - accuracy: 0.3250
Epoch 8/20
7/7 [==============================] - 0s 4ms/step - loss: 1.6242 - accuracy: 0.4000
Epoch 9/20
7/7 [==============================] - 0s 4ms/step - loss: 1.5990 - accuracy: 0.3800
Epoch 10/20
7/7 [==============================] - 0s 5ms/step - loss: 1.5378 - accuracy: 0.4250
Epoch 11/20
7/7 [==============================] - 0s 4ms/step - loss: 1.5167 - accuracy: 0.4400
Epoch 12/20
7/7 [==============================] - 0s 4ms/step - loss: 1.4500 - accuracy: 0.4950
Epoch 13/20
7/7 [==============================] - 0s 4ms/step - loss: 1.4349 - accuracy: 0.4700
Epoch 14/20
7/7 [==============================] - 0s 4ms/step - loss: 1.3322 - accuracy: 0.5550
Epoch 15/20
7/7 [==============================] - 0s 4ms/step - loss: 1.3048 - accuracy: 0.5100
Epoch 16/20
7/7 [==============================] - 0s 4ms/step - loss: 1.2838 - accuracy: 0.5300
Epoch 17/20
7/7 [==============================] - 0s 4ms/step - loss: 1.1745 - accuracy: 0.6100
Epoch 18/20
7/7 [==============================] - 0s 4ms/step - loss: 1.1374 - accuracy: 0.6350
Epoch 19/20
7/7 [==============================] - 0s 4ms/step - loss: 1.0833 - accuracy: 0.6700
Epoch 20/20
7/7 [==============================] - 0s 4ms/step - loss: 1.0738 - accuracy: 0.6400
68/68 [==============================] - 0s 3ms/step - loss: 1.1823 - accuracy: 0.5580

*** Test accuracy with 200 Examples: 0.558 ***

Epoch 1/20
101/101 [==============================] - 0s 4ms/step - loss: 0.9714 - accuracy: 0.6530
Epoch 2/20
101/101 [==============================] - 0s 4ms/step - loss: 0.7162 - accuracy: 0.7322
Epoch 3/20
101/101 [==============================] - 0s 4ms/step - loss: 0.5928 - accuracy: 0.7803
Epoch 4/20
101/101 [==============================] - 0s 4ms/step - loss: 0.5482 - accuracy: 0.7905
Epoch 5/20
101/101 [==============================] - 0s 4ms/step - loss: 0.5098 - accuracy: 0.8153
Epoch 6/20
101/101 [==============================] - 0s 4ms/step - loss: 0.4793 - accuracy: 0.8209
Epoch 7/20
101/101 [==============================] - 0s 4ms/step - loss: 0.4575 - accuracy: 0.8256
Epoch 8/20
101/101 [==============================] - 0s 4ms/step - loss: 0.4493 - accuracy: 0.8259
Epoch 9/20
101/101 [==============================] - 0s 4ms/step - loss: 0.4058 - accuracy: 0.8520
Epoch 10/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3932 - accuracy: 0.8554
Epoch 11/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3867 - accuracy: 0.8569
Epoch 12/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3635 - accuracy: 0.8653
Epoch 13/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3533 - accuracy: 0.8672
Epoch 14/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3310 - accuracy: 0.8771
Epoch 15/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3408 - accuracy: 0.8749
Epoch 16/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3270 - accuracy: 0.8827
Epoch 17/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3143 - accuracy: 0.8842
Epoch 18/20
101/101 [==============================] - 0s 4ms/step - loss: 0.3067 - accuracy: 0.8873
Epoch 19/20
101/101 [==============================] - 1s 5ms/step - loss: 0.3094 - accuracy: 0.8818
Epoch 20/20
101/101 [==============================] - 0s 4ms/step - loss: 0.2959 - accuracy: 0.8926
68/68 [==============================] - 0s 4ms/step - loss: 0.6029 - accuracy: 0.7916

*** Test accuracy with All Examples: 0.792 ***

Report the performance of our Glove Model above which uses the pre-trained word embeddings without fine-tuning. Comment on this performance. Please propose an explanation for why you think GloVe did not perform as well as BoW.

**<font color='red'>Your Answer Here</font>**

_Please replace the table below with your numbers_

* 200 Examples: 55.8%
* All Examples: 79.5%

_Please replace this text with your response_.

_GloVe without fine-tuning does not perform as well as BoW for both 200 examples and all examples. There are a couple possible explanations for this. GloVe vectors are trained on Wikipedia data, which may not accurate represent the meaning of words in the newsgroup dataset. Averaging the vectors for each word can drown out a lot of signal, if many words like "the" appear._

# Problem 3: GloVe with Fine Tuning [30 Points]

In problem 2, we did not fine-tune the word embeddings from GloVe. We simply downloaded them from the internet and used them as-is. In this question, we will fine-tune the embeddings to the training data set.

## Part (a): Why Fine Tuning is Needed [10 Points]

The goal of this part is to motivate why fine tuning of the word embeddings is necessary. In the process, we will understand why BoW is able to perform so well over GloVe.

The 20-newsgroup dataset consists of posts from a news discussion forum (from back in the day). Each of these posts look like an email, with a From: someone@email.com and subject lines. This is called the **header** of the post. Similarly, the email also has a **footer**, which typically consists of the author's name and affiliation. Consider one of the training examples shown below:

In [ ]:
print(train_df['text'][2101])

From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: HLV for Fred (was Re: Prefab Space Station?)
Article-I.D.: zoo.C51875.67p
Organization: U of Toronto Zoology
Lines: 28

In article <C5133A.Gzx@news.cso.uiuc.edu> jbh55289@uxa.cso.uiuc.edu (Josh Hopkins) writes:
>>>Titan IV launches ain't cheap
>>Granted. But that's because titan IV's are bought by the governemnt. Titan
>>III is actually the cheapest way to put a pound in space of all US expendable
>>launchers.
>
>In that case it's rather ironic that they are doing so poorly on the commercial
>market.  Is there a single Titan III on order?

The problem with Commercial Titan is that MM has made little or no attempt
to market it.  They're basically happy with their government business and
don't want to have to learn how to sell commercially.

A secondary problem is that it is a bit big.  They'd need to go after
multi-satellite launches, a la Ariane, and that complicates the marketing
task quite significantly.

They also had some problems with launch facilities at just the wrong time
to get them started properly.  If memory serves, the pad used for the Mars
Observer launch had just come out of heavy refurbishment work that had
prevented launches from it for a year or so.

There have been a few CT launches.  Mars Observer was one of them.  So
was that stranded Intelsat, and at least one of its brothers that reached
orbit properly.
--
All work is one man's work.             | Henry Spencer @ U of Toronto Zoology
                    - Kipling           |  henry@zoo.toronto.edu  utzoo!henry

The header would be

```
From: henry@zoo.toronto.edu (Henry Spencer)
Subject: Re: HLV for Fred (was Re: Prefab Space Station?)
Article-I.D.: zoo.C51875.67p
Organization: U of Toronto Zoology
Lines: 28
```

and the footer is

```
All work is one man's work.             | Henry Spencer @ U of Toronto Zoology
                    - Kipling           |  henry@zoo.toronto.edu  utzoo!henry
```

Note that this document belongs to the topic **sci.space** (i.e. astronomy).

Recall the text vectorization layer from Problem 1(a). An interesting token that appears in our vocabulary space is the token `henryzootorontoedu`, appearing at index 1121. This token also appears in the example text above.

In [ ]:
idx = text_vectorization_glove.get_vocabulary().index('henryzootorontoedu')
print('Token number %d is henryzootorontoedu' % idx)

Token number 1121 is henryzootorontoedu

This token actually appears in quite a few of the training examples. Notice that all of the labels of these documents is 4, corresponding to the category **sci.space**

In [ ]:
train_df.loc[np.where(X_train_glove == idx)[0]]

                                                   text  label
211   From: keithley@apple.com (Craig Keithley)\nSub...      4
219   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
271   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
271   From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
274   From: sysmgr@king.eng.umd.edu (Doug Mohney)\nS...      4
...                                                 ...    ...
2874  From: dong@oakhill.sps.mot.com (Don M. Gibson)...      4
2960  From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
2960  From: henry@zoo.toronto.edu (Henry Spencer)\nS...      4
3197  From: Leigh Palmer <palmer@sfu.ca>\nSubject: R...      4
3207  From: John Lussmyer <dragon@angus.mi.org>\nSub...      4

[89 rows x 2 columns]

Looking at our GloVe embeddings, the embedding for `henryzootorontoedu` is the all zeros vector.

In [ ]:
print('The embedding for token %d is' % idx, embedding_matrix[idx, :])

The embedding for token 1121 is [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Using the information above regarding this token `henryzootorontoedu`, please explain why BoW has an advantage of GloVe (with no fine-tuning). What do you think will happen to the embedding of `henryzootorontoedu` if we do perform fine-tuning?

<font color='red'>**Your Answer**</font>

_Please replace this text with your answer_

_We see that the token `henryzootorontoedu` (Token 1121) is highly correlated with the sci.space category. The bag of words will learn this very quickly. However, GloVe with pre-trained embeddings will not learn this. Since `henryzootorontoedu` is not one of the 400,000 English words that we have an embedding for, it receives the vector of all zeros. Therefore, for GloVe, the presence of of `henryzootorontoedu` will have no impact even though the word is highly predictive of the sci.space class. When we fine-tune the embeddings, very likely the token `henryzootorontoedu` will have a non-zero embedding and have an embedding that is similar to other words from the sci.space class (e.g. Titan, satellite, Mars)_

## Part (b): Stripping the Header [10 Points]

It turns out that we can strip the header and footer from the training and testing examples pretty easily. For example, the same document above is now shown below:

In [ ]:
newsgroups_train_raw = fetch_20newsgroups(subset='train', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'], remove=('headers', 'footers', 'quotes'))
newsgroups_test_raw = fetch_20newsgroups(subset='test', categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space', 'sci.med', 'rec.autos'], remove=('headers', 'footers', 'quotes'))

train_df_raw = pd.DataFrame({'text': newsgroups_train_raw.data, 'label': newsgroups_train_raw.target})
test_df_raw = pd.DataFrame({'text': newsgroups_test_raw.data, 'label': newsgroups_test_raw.target})

print(train_df_raw['text'][2101])

The problem with Commercial Titan is that MM has made little or no attempt
to market it.  They're basically happy with their government business and
don't want to have to learn how to sell commercially.

A secondary problem is that it is a bit big.  They'd need to go after
multi-satellite launches, a la Ariane, and that complicates the marketing
task quite significantly.

They also had some problems with launch facilities at just the wrong time
to get them started properly.  If memory serves, the pad used for the Mars
Observer launch had just come out of heavy refurbishment work that had
prevented launches from it for a year or so.

There have been a few CT launches.  Mars Observer was one of them.  So
was that stranded Intelsat, and at least one of its brothers that reached
orbit properly.

Now, copy the code from Problem 1(a), to train a BoW model, but this time adapt the corpus and use `train_df_raw` and `test_df_raw` instead of `train_df` and `test_df`.

In [ ]:
# First, we configure a Text Vectorization layer using the default
# standardization and multi-hot encoding

# Set the maximum number of tokens (which is the size of the vocabulary) to 1000
max_tokens = 2000

# Configure the text vectorization layer
text_vectorization = keras.layers.TextVectorization(
    max_tokens=max_tokens,
    output_mode = 'multi_hot',
    standardize = 'lower_and_strip_punctuation',
    ngrams=1,
)

# Let's adapt the Text Vectorization layer using the training corpus
text_vectorization.adapt(train_df_raw['text'])

# We vectorize our input with the adapted Text Vectorization layer
X_train_raw = text_vectorization(train_df_raw['text'])
X_test_raw = text_vectorization(test_df_raw['text'])

# Build a baseline NN model with one hidden layer that has 8 neurons.
inputs = keras.Input(shape=(max_tokens, )) # Size of the input layer is the size of the vocabulary
x = keras.layers.Dense(128, activation="relu")(inputs) # only hidden layer
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)

bow_model_raw = keras.Model(inputs, outputs)
bow_model_raw.summary()

# Compile model using Adam
bow_model_raw.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Build a baseline NN model with one hidden layer that has 8 neurons.
inputs = keras.Input(shape=(max_tokens, )) # Size of the input layer is the size of the vocabulary
x = keras.layers.Dense(128, activation="relu")(inputs) # only hidden layer
outputs = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)

bow_model_raw = keras.Model(inputs, outputs)
bow_model_raw.summary()

# Compile model using Adam
bow_model_raw.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 10 epochs and batch size of 32
bow_model_raw.fit(
    x=X_train_raw[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples: %.4f ***\n" % bow_model_raw.evaluate(x=X_test_raw, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
bow_model_raw.fit(
    x=X_train_raw, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples % .4f ***\n" % bow_model_raw.evaluate(x=X_test_raw, y=y_test)[1])

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_4 (InputLayer)        [(None, 2000)]            0

 dense_7 (Dense)             (None, 128)               256128

 dense_8 (Dense)             (None, 6)                 774

=================================================================
Total params: 256902 (1003.52 KB)
Trainable params: 256902 (1003.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_5 (InputLayer)        [(None, 2000)]            0

 dense_9 (Dense)             (None, 128)               256128

 dense_10 (Dense)            (None, 6)                 774

=================================================================
Total params: 256902 (1003.52 KB)
Trainable params: 256902 (1003.52 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
7/7 [==============================] - 1s 4ms/step - loss: 1.7801 - accuracy: 0.2350
Epoch 2/20
7/7 [==============================] - 0s 3ms/step - loss: 1.4262 - accuracy: 0.6450
Epoch 3/20
7/7 [==============================] - 0s 3ms/step - loss: 1.1821 - accuracy: 0.8900
Epoch 4/20
7/7 [==============================] - 0s 3ms/step - loss: 0.9576 - accuracy: 0.9250
Epoch 5/20
7/7 [==============================] - 0s 3ms/step - loss: 0.7700 - accuracy: 0.9450
Epoch 6/20
7/7 [==============================] - 0s 3ms/step - loss: 0.6249 - accuracy: 0.9600
Epoch 7/20
7/7 [==============================] - 0s 3ms/step - loss: 0.5077 - accuracy: 0.9700
Epoch 8/20
7/7 [==============================] - 0s 4ms/step - loss: 0.4210 - accuracy: 0.9800
Epoch 9/20
7/7 [==============================] - 0s 3ms/step - loss: 0.3532 - accuracy: 0.9850
Epoch 10/20
7/7 [==============================] - 0s 4ms/step - loss: 0.3027 - accuracy: 0.9850
Epoch 11/20
7/7 [==============================] - 0s 3ms/step - loss: 0.2618 - accuracy: 0.9850
Epoch 12/20
7/7 [==============================] - 0s 3ms/step - loss: 0.2307 - accuracy: 0.9850
Epoch 13/20
7/7 [==============================] - 0s 3ms/step - loss: 0.2022 - accuracy: 0.9850
Epoch 14/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1816 - accuracy: 0.9850
Epoch 15/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1634 - accuracy: 0.9850
Epoch 16/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1490 - accuracy: 0.9850
Epoch 17/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1369 - accuracy: 0.9850
Epoch 18/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1272 - accuracy: 0.9850
Epoch 19/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1181 - accuracy: 0.9850
Epoch 20/20
7/7 [==============================] - 0s 3ms/step - loss: 0.1105 - accuracy: 0.9850
68/68 [==============================] - 0s 2ms/step - loss: 1.3482 - accuracy: 0.4984

*** Test accuracy with 200 Examples: 0.4984 ***

Epoch 1/20
101/101 [==============================] - 0s 3ms/step - loss: 0.8951 - accuracy: 0.6800
Epoch 2/20
101/101 [==============================] - 0s 3ms/step - loss: 0.4277 - accuracy: 0.8678
Epoch 3/20
101/101 [==============================] - 0s 3ms/step - loss: 0.3112 - accuracy: 0.9103
Epoch 4/20
101/101 [==============================] - 0s 3ms/step - loss: 0.2418 - accuracy: 0.9348
Epoch 5/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1979 - accuracy: 0.9513
Epoch 6/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1671 - accuracy: 0.9593
Epoch 7/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1446 - accuracy: 0.9631
Epoch 8/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1283 - accuracy: 0.9671
Epoch 9/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1160 - accuracy: 0.9702
Epoch 10/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1062 - accuracy: 0.9718
Epoch 11/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0989 - accuracy: 0.9724
Epoch 12/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0932 - accuracy: 0.9727
Epoch 13/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0885 - accuracy: 0.9739
Epoch 14/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0849 - accuracy: 0.9733
Epoch 15/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0819 - accuracy: 0.9733
Epoch 16/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0792 - accuracy: 0.9736
Epoch 17/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0772 - accuracy: 0.9739
Epoch 18/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0754 - accuracy: 0.9739
Epoch 19/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0741 - accuracy: 0.9739
Epoch 20/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0728 - accuracy: 0.9739
68/68 [==============================] - 0s 5ms/step - loss: 1.5832 - accuracy: 0.6755

*** Test accuracy with All Examples  0.6755 ***

Fill in the table below with the test accuracy. Comment on how BoW's performance changes when trained and tested on the 20-newsgroup dataset _without headers and footers_. Does this support our hypothesis from Part (a)?

<font color='red'>**Your Answer Here**</font>

Accuracy Scores
* 200 Training Examples: 49.8%
* All Examples: 67.5%

_Please replace this with your answer_

_The performance has gone down significantly. This supports our hypothesis from (a). When we removed a lot of the emails and people's names from the text, BoW's performance declines significantly. This implies that BoW was previously using these names to perform classification._

## Part (c): Build a Model [10 Points]

Now, let's fine tune the GloVe embeddings for our particular dataset. Copy your code from Problem 2, but now change `trainable=True` in `embedding_layer`. Do not change anything else about the model.

In [ ]:
embedding_layer = keras.layers.Embedding(
    max_tokens,
    embedding_dim,
    embeddings_initializer= keras.initializers.Constant(embedding_matrix),
    trainable=True,
    mask_zero=True,
)

inputs = keras.Input(shape=(max_length,))
x = embedding_layer(inputs)

x = keras.layers.GlobalAveragePooling1D()(x)
x = keras.layers.Dense(128, activation="relu")(x) # only hidden layer
x = keras.layers.Dropout(0.2)(x)
x = keras.layers.Dense(128, activation="relu")(x) # only hidden layer
x = keras.layers.Dropout(0.2)(x)

outputs = keras.layers.Dense(y_train.shape[1], activation="sigmoid")(x) # output layer

glove_model_tuned = keras.Model(inputs, outputs)
glove_model_tuned.summary()

# Compile model using Adam
glove_model_tuned.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy']
)

# Fit model on the training data with 10 epochs and batch size of 32
glove_model_tuned.fit(
    x=X_train_glove[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples %.4f ***\n" % glove_model_tuned.evaluate(x=X_test_glove, y=y_test)[1])

# Fit model on the training data with 10 epochs and batch size of 32
glove_model_tuned.fit(
    x=X_train_glove, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples %.4f ***\n" % glove_model_tuned.evaluate(x=X_test_glove, y=y_test)[1])

Model: "model_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_6 (InputLayer)        [(None, 400)]             0

 embedding_1 (Embedding)     (None, 400, 300)          600000

 global_average_pooling1d_1  (None, 300)               0
  (GlobalAveragePooling1D)

 dense_11 (Dense)            (None, 128)               38528

 dropout_2 (Dropout)         (None, 128)               0

 dense_12 (Dense)            (None, 128)               16512

 dropout_3 (Dropout)         (None, 128)               0

 dense_13 (Dense)            (None, 6)                 774

=================================================================
Total params: 655814 (2.50 MB)
Trainable params: 655814 (2.50 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
7/7 [==============================] - 4s 332ms/step - loss: 1.7954 - accuracy: 0.1800
Epoch 2/20
7/7 [==============================] - 2s 290ms/step - loss: 1.7703 - accuracy: 0.2250
Epoch 3/20
7/7 [==============================] - 2s 272ms/step - loss: 1.7302 - accuracy: 0.3000
Epoch 4/20
7/7 [==============================] - 1s 152ms/step - loss: 1.7111 - accuracy: 0.3350
Epoch 5/20
7/7 [==============================] - 1s 179ms/step - loss: 1.6743 - accuracy: 0.3600
Epoch 6/20
7/7 [==============================] - 1s 151ms/step - loss: 1.6385 - accuracy: 0.3250
Epoch 7/20
7/7 [==============================] - 1s 179ms/step - loss: 1.5957 - accuracy: 0.4100
Epoch 8/20
7/7 [==============================] - 1s 123ms/step - loss: 1.5174 - accuracy: 0.5050
Epoch 9/20
7/7 [==============================] - 2s 230ms/step - loss: 1.4394 - accuracy: 0.5700
Epoch 10/20
7/7 [==============================] - 1s 194ms/step - loss: 1.3295 - accuracy: 0.6100
Epoch 11/20
7/7 [==============================] - 1s 192ms/step - loss: 1.2329 - accuracy: 0.6500
Epoch 12/20
7/7 [==============================] - 1s 200ms/step - loss: 1.0939 - accuracy: 0.7350
Epoch 13/20
7/7 [==============================] - 1s 151ms/step - loss: 1.0030 - accuracy: 0.7450
Epoch 14/20
7/7 [==============================] - 1s 149ms/step - loss: 0.8791 - accuracy: 0.7350
Epoch 15/20
7/7 [==============================] - 1s 117ms/step - loss: 0.7530 - accuracy: 0.8250
Epoch 16/20
7/7 [==============================] - 1s 147ms/step - loss: 0.6378 - accuracy: 0.8600
Epoch 17/20
7/7 [==============================] - 1s 121ms/step - loss: 0.5505 - accuracy: 0.8800
Epoch 18/20
7/7 [==============================] - 1s 122ms/step - loss: 0.4557 - accuracy: 0.9300
Epoch 19/20
7/7 [==============================] - 1s 89ms/step - loss: 0.3791 - accuracy: 0.9350
Epoch 20/20
7/7 [==============================] - 1s 92ms/step - loss: 0.3400 - accuracy: 0.9250
68/68 [==============================] - 0s 3ms/step - loss: 0.8885 - accuracy: 0.6816

*** Test accuracy with 200 Examples 0.6816 ***

Epoch 1/20
101/101 [==============================] - 12s 114ms/step - loss: 0.6208 - accuracy: 0.7716
Epoch 2/20
101/101 [==============================] - 6s 55ms/step - loss: 0.3742 - accuracy: 0.8622
Epoch 3/20
101/101 [==============================] - 4s 43ms/step - loss: 0.2517 - accuracy: 0.9069
Epoch 4/20
101/101 [==============================] - 7s 66ms/step - loss: 0.1684 - accuracy: 0.9448
Epoch 5/20
101/101 [==============================] - 3s 30ms/step - loss: 0.1118 - accuracy: 0.9631
Epoch 6/20
101/101 [==============================] - 2s 20ms/step - loss: 0.0740 - accuracy: 0.9764
Epoch 7/20
101/101 [==============================] - 3s 27ms/step - loss: 0.0568 - accuracy: 0.9829
Epoch 8/20
101/101 [==============================] - 2s 15ms/step - loss: 0.0433 - accuracy: 0.9879
Epoch 9/20
101/101 [==============================] - 1s 12ms/step - loss: 0.0339 - accuracy: 0.9910
Epoch 10/20
101/101 [==============================] - 2s 22ms/step - loss: 0.0264 - accuracy: 0.9932
Epoch 11/20
101/101 [==============================] - 2s 24ms/step - loss: 0.0155 - accuracy: 0.9972
Epoch 12/20
101/101 [==============================] - 1s 13ms/step - loss: 0.0098 - accuracy: 0.9991
Epoch 13/20
101/101 [==============================] - 2s 22ms/step - loss: 0.0075 - accuracy: 0.9997
Epoch 14/20
101/101 [==============================] - 2s 16ms/step - loss: 0.0065 - accuracy: 0.9994
Epoch 15/20
101/101 [==============================] - 1s 12ms/step - loss: 0.0059 - accuracy: 0.9991
Epoch 16/20
101/101 [==============================] - 1s 10ms/step - loss: 0.0043 - accuracy: 0.9994
Epoch 17/20
101/101 [==============================] - 1s 8ms/step - loss: 0.0040 - accuracy: 1.0000
Epoch 18/20
101/101 [==============================] - 1s 8ms/step - loss: 0.0032 - accuracy: 0.9997
Epoch 19/20
101/101 [==============================] - 1s 8ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 20/20
101/101 [==============================] - 1s 13ms/step - loss: 0.0022 - accuracy: 1.0000
68/68 [==============================] - 0s 3ms/step - loss: 0.7803 - accuracy: 0.8415

*** Test accuracy with All Examples 0.8415 ***

Report the performance of our Glove Model above with fine tuning. Comment on this performance and compare it to that of the GloVe model without fine tuning. Explain when fine-tuning can be helpful and/or hurtful.

**<font color='red'>Your Answer Here</font>**

_Please replace the table below with your numbers_

* 200 Examples: 68.2% (Your answer may vary from this)
* All Examples: 84.1%

_Please replace this text with your response_.

_Answer. Fine tuning made the performance better for All Examples and worse for 200 Examples. This makes sense because when we have only a few examples, fine-tuning just leads to a lot of overfitting. On the other hand, when we have many examples, fine-tuning can lead to a better embeddings that are tailored towards a particular classification task that cap and thus better overall performance._

The embedding for the token `henryzootorontoedu` is now no longer all 0's. Nice!

In [ ]:
print('The embedding for token %d is' % idx, glove_model_tuned.layers[1].weights[0][idx, :])

The embedding for token 1121 is tf.Tensor(
[ 0.04548174  0.07106574  0.12559451  0.01939604 -0.113691    0.07588904
 -0.1142942  -0.13795526 -0.00836113 -0.11620262  0.16121845 -0.05949525
  0.11007643 -0.12671092 -0.15571752  0.10972071  0.12101343  0.13156746
 -0.08381724  0.01628437 -0.08191272 -0.06775402 -0.08077831  0.15563102
  0.11042489  0.13917764 -0.10874247  0.10440496 -0.12844928  0.10008034
  0.15958744  0.09053869 -0.1862929   0.06595966 -0.06099972 -0.10755301
  0.11991861  0.10591989  0.11384564  0.10832665 -0.09684828 -0.06728903
  0.00923315  0.06172772 -0.1374209   0.07383049  0.03174763  0.12510315
 -0.05039083 -0.13083616 -0.04695299  0.05505094 -0.11015958 -0.10422369
 -0.13049425  0.07598031  0.16093646  0.0624091  -0.08583169 -0.07189132
 -0.09192856 -0.04763409 -0.0336896  -0.10931462  0.10193513 -0.06472947
  0.06214646 -0.13656795 -0.12682696 -0.07962221  0.1292712   0.05727947
  0.11996164  0.04719196  0.08600345  0.08034435  0.01130225  0.13435683
  0.05538122  0.10340713 -0.11023746  0.10617231 -0.13548861  0.07830794
 -0.04543464  0.16362908 -0.05024144  0.09038042  0.09723032 -0.10292064
  0.08242425 -0.1069437   0.066421    0.11552827 -0.13442074 -0.13488865
 -0.08569328  0.08316281 -0.09525941 -0.08013875 -0.0424043   0.0593093
 -0.10697713  0.09180741  0.10746629  0.02335703 -0.13858445 -0.1203017
  0.08343946  0.01541846 -0.12205009  0.06587861  0.10007638  0.08725377
 -0.10616516  0.04127008 -0.05083992  0.05909104  0.18469487 -0.11504599
  0.09895163 -0.04390044  0.00037623  0.01838405 -0.05934438  0.10107123
 -0.12886158  0.13284509  0.07770847  0.15312414 -0.11996725  0.10064955
  0.11244722 -0.11027823  0.04437608 -0.15014912 -0.13792397  0.11757277
 -0.13103174 -0.11717603 -0.11711522 -0.16415007  0.02975449  0.15479939
  0.06148523 -0.05707846 -0.0474912   0.16486154  0.11190828 -0.07604307
  0.0534979   0.08136348 -0.02114788  0.0056262   0.1158895  -0.08226379
 -0.11424528  0.14902979 -0.1659805  -0.14454429  0.10073686 -0.08492672
  0.12488244  0.06637426  0.13097371 -0.12293928  0.0059033  -0.12331124
  0.1253759   0.10567595 -0.0835686  -0.11052331  0.05953929 -0.0981956
 -0.10637145  0.12160216 -0.18584013 -0.01608513 -0.13311477 -0.12650383
  0.04961983  0.06969252  0.13087116  0.12100244 -0.1004036  -0.04243023
 -0.06201464 -0.05726604 -0.08717768 -0.14617428  0.09343361  0.0140087
  0.12292258  0.1037405   0.06905912  0.11121017  0.06107512  0.09791401
  0.0929432  -0.12874901 -0.00151065 -0.10171204 -0.14183368  0.05058785
 -0.11378481 -0.03056294 -0.00405181  0.1126963   0.13485914 -0.08840912
  0.08310574 -0.15728293 -0.05734764 -0.12244718  0.0576598  -0.12997566
  0.05160979 -0.13219942 -0.15757534  0.07438048  0.11202227 -0.10621815
 -0.12325685  0.16337627  0.00709428 -0.10360827 -0.04113447 -0.0513393
  0.01481525  0.09815092  0.15568627  0.14181414 -0.10348847  0.01587316
 -0.02497056 -0.1315758  -0.12256096  0.10646838  0.12502208  0.08838163
  0.12639852 -0.12283868  0.04008408 -0.14567016 -0.03841206 -0.04920946
  0.07503932  0.16876076  0.02055819  0.06803162 -0.10950907  0.13561432
 -0.12255546  0.11551056 -0.09839101  0.11786559 -0.05507477 -0.14787565
 -0.01642286  0.12955876  0.16530044  0.019264    0.1300117  -0.13965182
  0.04996734 -0.11544053 -0.14568512  0.13949414  0.12409208  0.15246779
  0.08078367  0.01614356  0.12928118 -0.06395674 -0.13763258 -0.00900228
 -0.11614006  0.09771078 -0.02941676 -0.11813443 -0.11044163  0.1595509
  0.14357665 -0.1461356  -0.05356855 -0.12661867 -0.11692426 -0.00417569
 -0.14699408  0.17438957  0.01112888 -0.10513957 -0.12888727  0.10325927
  0.15144995  0.09117096 -0.14158821 -0.12705599 -0.16010773 -0.14457019], shape=(300,), dtype=float32)

# Problem 4: BERT Transformer Model [15 Points]

Finally, we use will a famous transformer pre-trained model called [Bert](https://en.wikipedia.org/wiki/BERT_(language_model)). Just like how ResNet was a pre-trained model for computer vision (image processing), BERT is a pre-trained model for natural language processing.

In [ ]:
!pip install -q -U tensorflow-text ## install the package for NLP tasks in tensorflow

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 22.2 MB/s eta 0:00:00

In [ ]:
import tensorflow_hub as hub
import tensorflow_text

bert_preprocess = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

bert_layers = 12
bert_units = 768
bert_heads = 12

bert_encoder = f'https://tfhub.dev/tensorflow/bert_en_uncased_L-{bert_layers}_H-{bert_units}_A-{bert_heads}/4'

Let's look to some examples of the text processing required for BERT:

In [ ]:
bert_preprocess_model = hub.KerasLayer(bert_preprocess)

text_test = ['This is comedy as it once was and comparing this with the two remakes.']
text_preprocessed = bert_preprocess_model(text_test)
print(f'Word Ids   : {text_preprocessed["input_word_ids"]}')

text_test = ['Although I rated this movie a 2 for showing a complete lack of effort in trying to create a quality horror film it was a 10 on the unintentional funny scale.']
text_preprocessed = bert_preprocess_model(text_test)
print(f'Word Ids   : {text_preprocessed["input_word_ids"]}')

Word Ids   : [[  101  2023  2003  4038  2004  2009  2320  2001  1998 13599  2023  2007
   1996  2048 12661  2015  1012   102     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]]
Word Ids   : [[  101  2348  1045  6758  2023  3185  1037  1016  2005  4760  1037  3143
   3768  1997  3947  1999  2667  2000  3443  1037  3737  5469  2143  2009
   2001  1037  2184  2006  1996  4895 18447  4765 19301  6057  4094  1012
    102     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0     0     0     0     0
      0     0     0     0     0     0     0     0]]

Notice how all examples start with the token `101` and end with `102` (and then followed by `[PAD]` tokens as indicated by 0). Those are special placeholder tokens that can be used for different purposes. For this exercise, we will only concern about the first one, and we will call this token the 'classification token', or `[CLS]`.

The two functions below are used to convert text into tokens (`bert_textvect`) and tokens into embeddings (`bert_features`). You do not need to understand exactly how the functions below work. Note that the following cell may take some time to run (around 5 minutes).

In [ ]:
max_length = 512
preprocessor = hub.load(bert_preprocess)
encoder = hub.KerasLayer(bert_encoder, trainable=False)

def bert_textvect(x):
    """
    Converts a list of strings into a list of tokens for BERT
    """
    input = keras.layers.Input(shape=(), dtype=tf.string)
    tokenized_input = hub.KerasLayer(preprocessor.tokenize)(input)
    bert_pack_inputs = hub.KerasLayer(preprocessor.bert_pack_inputs, arguments=dict(seq_length=max_length))
    output = bert_pack_inputs([tokenized_input])
    model = keras.Model(input, output)
    result = model.predict(x)
    return result

def bert_features(x):
    """
    Converts the list of tokens into 768-dimensional embeddings for BERT.
    """
    inputs = dict(
    input_word_ids=keras.layers.Input(shape=(max_length,), dtype=tf.int32),
    input_mask=keras.layers.Input(shape=(max_length,), dtype=tf.int32),
    input_type_ids=keras.layers.Input(shape=(max_length,), dtype=tf.int32),
    )

    output = encoder(inputs)['sequence_output'][:, 0, :]
    model = keras.Model(inputs, output)
    return model.predict(x)

X_bert_train = bert_textvect(train_df['text'])
X_bert_test = bert_textvect(test_df['text'])

features_train = bert_features(X_bert_train)
features_test = bert_features(X_bert_test)

features_train.shape

101/101 [==============================] - 8s 74ms/step
68/68 [==============================] - 7s 104ms/step
101/101 [==============================] - 138s 1s/step
68/68 [==============================] - 91s 1s/step

(3222, 768)

Next, we'll use the BERT output embedding for the CLS token as input to train a simple neural net.

In [ ]:
input = keras.Input(shape=(bert_units, ))

x = keras.layers.Dense(128, activation='relu')(input)
x = keras.layers.Dropout(0.1)(x)
x = keras.layers.Dense(128, activation='relu')(x)
x = keras.layers.Dropout(0.1)(x)

output = keras.layers.Dense(y_train.shape[1], activation='softmax')(x)

# Model
bert_model = keras.Model(input, output)
bert_model.summary()

bert_model.compile(optimizer="adam",
              loss="categorical_crossentropy",
              metrics=["accuracy"])

bert_model.fit(
    x=features_train[:200], y=y_train[:200],
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with 200 Examples %.4f ***\n" % bert_model.evaluate(x=features_test, y=y_test)[1])

bert_model.fit(
    x=features_train, y=y_train,
    epochs=20, batch_size=32,
    verbose=1,
)

print("\n*** Test accuracy with All Examples %.4f ***\n" % bert_model.evaluate(x=features_test, y=y_test)[1])

Model: "model_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 input_15 (InputLayer)       [(None, 768)]             0

 dense_14 (Dense)            (None, 128)               98432

 dropout_4 (Dropout)         (None, 128)               0

 dense_15 (Dense)            (None, 128)               16512

 dropout_5 (Dropout)         (None, 128)               0

 dense_16 (Dense)            (None, 6)                 774

=================================================================
Total params: 115718 (452.02 KB)
Trainable params: 115718 (452.02 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
Epoch 1/20
7/7 [==============================] - 1s 4ms/step - loss: 1.7722 - accuracy: 0.2250
Epoch 2/20
7/7 [==============================] - 0s 4ms/step - loss: 1.5284 - accuracy: 0.4600
Epoch 3/20
7/7 [==============================] - 0s 4ms/step - loss: 1.3674 - accuracy: 0.5250
Epoch 4/20
7/7 [==============================] - 0s 4ms/step - loss: 1.2418 - accuracy: 0.5900
Epoch 5/20
7/7 [==============================] - 0s 4ms/step - loss: 1.0186 - accuracy: 0.6950
Epoch 6/20
7/7 [==============================] - 0s 5ms/step - loss: 0.8831 - accuracy: 0.7850
Epoch 7/20
7/7 [==============================] - 0s 4ms/step - loss: 0.7263 - accuracy: 0.7500
Epoch 8/20
7/7 [==============================] - 0s 4ms/step - loss: 0.6182 - accuracy: 0.8200
Epoch 9/20
7/7 [==============================] - 0s 5ms/step - loss: 0.4716 - accuracy: 0.8850
Epoch 10/20
7/7 [==============================] - 0s 4ms/step - loss: 0.4200 - accuracy: 0.8700
Epoch 11/20
7/7 [==============================] - 0s 4ms/step - loss: 0.3756 - accuracy: 0.9200
Epoch 12/20
7/7 [==============================] - 0s 4ms/step - loss: 0.3460 - accuracy: 0.8850
Epoch 13/20
7/7 [==============================] - 0s 4ms/step - loss: 0.2770 - accuracy: 0.9450
Epoch 14/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1888 - accuracy: 0.9550
Epoch 15/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1769 - accuracy: 0.9650
Epoch 16/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1682 - accuracy: 0.9850
Epoch 17/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1396 - accuracy: 0.9850
Epoch 18/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1267 - accuracy: 0.9850
Epoch 19/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1522 - accuracy: 0.9500
Epoch 20/20
7/7 [==============================] - 0s 4ms/step - loss: 0.1263 - accuracy: 0.9650
68/68 [==============================] - 0s 3ms/step - loss: 0.7873 - accuracy: 0.7296

*** Test accuracy with 200 Examples 0.7296 ***

Epoch 1/20
101/101 [==============================] - 0s 3ms/step - loss: 0.5312 - accuracy: 0.8014
Epoch 2/20
101/101 [==============================] - 0s 3ms/step - loss: 0.4001 - accuracy: 0.8433
Epoch 3/20
101/101 [==============================] - 0s 3ms/step - loss: 0.3313 - accuracy: 0.8740
Epoch 4/20
101/101 [==============================] - 0s 3ms/step - loss: 0.2837 - accuracy: 0.8883
Epoch 5/20
101/101 [==============================] - 0s 3ms/step - loss: 0.2496 - accuracy: 0.9081
Epoch 6/20
101/101 [==============================] - 0s 3ms/step - loss: 0.2374 - accuracy: 0.9106
Epoch 7/20
101/101 [==============================] - 0s 3ms/step - loss: 0.2194 - accuracy: 0.9212
Epoch 8/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1852 - accuracy: 0.9311
Epoch 9/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1817 - accuracy: 0.9314
Epoch 10/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1422 - accuracy: 0.9444
Epoch 11/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1343 - accuracy: 0.9534
Epoch 12/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1298 - accuracy: 0.9519
Epoch 13/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1137 - accuracy: 0.9597
Epoch 14/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1000 - accuracy: 0.9646
Epoch 15/20
101/101 [==============================] - 0s 3ms/step - loss: 0.1021 - accuracy: 0.9634
Epoch 16/20
101/101 [==============================] - 0s 3ms/step - loss: 0.0765 - accuracy: 0.9745
Epoch 17/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0605 - accuracy: 0.9804
Epoch 18/20
101/101 [==============================] - 0s 5ms/step - loss: 0.0573 - accuracy: 0.9826
Epoch 19/20
101/101 [==============================] - 0s 4ms/step - loss: 0.0978 - accuracy: 0.9609
Epoch 20/20
101/101 [==============================] - 0s 5ms/step - loss: 0.0925 - accuracy: 0.9640
68/68 [==============================] - 0s 4ms/step - loss: 0.7694 - accuracy: 0.8051

*** Test accuracy with All Examples 0.8051 ***

Fill in the table below with the accuracies from above. Comment on the performance of the model relative to the BoW and GloVe models. Does BERT suffer from the same shortcoming as GloVe regarding tokens like `henryzootorontoedu`?

<font color='red'>**Your Answer Here**</font>

BERT Model Accuracy
* 200 Examples: 72.9%
* All Examples: 80.5%

_Replace this with your answer_

_The performance of BERT with just 200 examples is an amazing 73.4%! Wow! None of the other models come close with only 200 examples. This truly shows the power of the transformer model. However, with all examples, BoW still performs the best, which is quite incredible for such a simple classification model. Intuitively, our news topic classification problem is just not that difficult of a problem. with enough training examples, BERT is a bit "overkill" and does not lead to any benefit over simple bag of words._

# Conclusion [5 Points]